-- Create contacts table in Supabase
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

-- Policy to allow anonymous users to insert contacts
CREATE POLICY "Allow anonymous inserts" 
ON public.contacts
FOR INSERT 
TO anon
WITH CHECK (true);

-- Policy to allow service role full access (for viewing contacts)
-- CREATE POLICY "Allow service role full access" 
-- ON public.contacts
-- FOR ALL
-- TO service_role
-- USING (true)
-- WITH CHECK (true);

-- Verify the table was created
SELECT * FROM public.contacts LIMIT 1;

