-- Create projects table in Supabase
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  live_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (if needed for authenticated access)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- Policy to allow public read access (viewing projects)
CREATE POLICY "Allow public read access" 
ON public.projects
FOR SELECT 
TO public
USING (true);

-- Policy to allow service role to insert/update/delete (for admin operations)
-- Only create this if you need admin access
-- CREATE POLICY "Allow service role full access" 
-- ON public.projects
-- FOR ALL
-- TO service_role
-- USING (true)
-- WITH CHECK (true);

-- Verify the table was created
SELECT * FROM public.projects LIMIT 1;

